Carteirinha/Controllers/CadastroController.cs
using Microsoft.AspNetCore.Mvc;
using Carteirinha.Data;
using Carteirinha.Models;
using System.Text;
using static System.Net.Mime.MediaTypeNames;
using System.Security.Cryptography.X509Certificates;

namespace Carteirinha.Controllers
{
    public class CadastroController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CadastroController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Cadastrar()
        {
            string sessionId = HttpContext.Session.Id;
            IEnumerable<Usuario> User = _context.Usuario;
            ViewBag.Tipo = "_Layout";
            bool logado = false;
            foreach (Usuario user_login in User)
            {
                if (user_login.Login == sessionId)
                {
                    logado = true;
                    ViewBag.Username = user_login.Username;
                    if (user_login.Username == "ADM")
                    {
                        if (user_login.Nome == "ADM")
                        {
                            ViewBag.Tipo = "_Layout_Adm";
                        }
                    }
                }

            }
            ViewBag.login = logado;
            return View();
        }
        [HttpPost]
        public IActionResult Cadastrar(Usuario novo_usuario, string Confirma_Senha)
        {
            IEnumerable<Usuario> usuarios = _context.Usuario;
            int invalidar = 0;

            foreach (Usuario usuario_existente in usuarios)
            {
                if (novo_usuario.Gmail == usuario_existente.Gmail)
                {
                    invalidar = 1;
                    ViewBag.M3 = "O gmail ja é existente";
                }
                if(novo_usuario.Username == usuario_existente.Username)
                {
                    invalidar = 1;

                    ViewBag.M1 = "Ja existe um usuario com esse apelido";
                }
            }
            if (novo_usuario.Senha != Confirma_Senha)
            {
                invalidar = 1;

                ViewBag.M2 = "As senhas não conferem";
            }
            if (invalidar == 0) { 
            Hash hash = new Hash(HashProvider.MD5);
            if (ModelState.IsValid) {
                novo_usuario.Senha = hash.GetHash(novo_usuario.Senha);
                    _context.Usuario.Add(novo_usuario);
                    _context.SaveChanges();
                    return RedirectToAction("Login", "Home"); 
            }
            }

            return View("Cadastrar");

        }
        }
    }

Carteirinha/Views/Cadastro/Cadastrar.cshtml
@model Usuario;
@{
    var permitido = ViewBag.Login;
    var usuario_logado = ViewBag.usuario;
    Layout = $"/Views/Shared/{ViewBag.Tipo}.cshtml";
}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;700&display=swap" rel="stylesheet">
<div class="container h-75 w-75 align-items-center">
<form method="post" asp-controller="Cadastro" asp-action="Cadastrar" class="">
    <div class="form-row row">
        <div class="form-group col-6">
            <label for="Nome">Nome Completo</label>
                <input asp-for="Nome" type="text" class="form-control" id="Nome" placeholder="Nome">
                <span asp-validation-for="Nome" class="text-warning"></span>
            </div>
            <div class="form-group col-6">
                <label for="Username">Apelido</label>
                <input asp-for="Username"  type="text" class="form-control" id="Nome" placeholder="Digite o apelido que irá usar no site">
                <span asp-validation-for="Username" class="text-warning"></span>
                @if (!string.IsNullOrEmpty(ViewBag.M1))
                {
                    <span id="mensagemErro" class="text-danger">@ViewBag.M1</span>
                }

            </div>
                <div class="form-group col-12 mb-2">
                    <label for="Email">Gmail</label>
                    <input asp-for="Gmail" type="email" class="form-control" id="Email" placeholder="Digite seu Gmail">
                    <span asp-validation-for="Gmail" class="text-warning"></span>
                    @if (!string.IsNullOrEmpty(ViewBag.M3))
                    {
                        <span id="mensagemErro" class="text-danger">@ViewBag.M3</span>
                    }

                </div>

    </div>
    <div class="form-row">
            <div class="form-group col-12">
                <label for="Senha">Senha</label>
                <input asp-for="Senha" type="password" class="form-control" id="Senha" placeholder="Digite sua senha">
                <span asp-validation-for="Senha" class="text-warning"></span>
            </div>
            <div class="form-group col-12">
                <label for="Confirma_Senha">Confirmar Senha</label>
                <input type="password" class="form-control" name="Confirma_Senha" id="Confirma_Senha" placeholder="Confirme sua senha">
                @if (!string.IsNullOrEmpty(ViewBag.M2))
                {
                    <span id="mensagemErro" class="text-danger">@ViewBag.M2</span>
                }
            </div>
</div>
<div class="text-center mt-2 mb-2">
    <button  type="submit" class="btn col-4 btn-primary">Confirmar</button>
        </div>
</form>
</div>